[package]
name = "figdriver"
version = "0.6.0"
authors = ["Claudio Matsuoka"]
edition = "2021"
description = "Render text as ASCII-art banners"
repository = "https://github.com/cmatsuoka/figdriver-rs"
license = "MIT"
keywords = ["ascii", "ascii-art", "terminal", "banner", "figlet"]
readme = "README.md"
include = [
        "/Cargo.toml",
        "/Cargo.lock",
        "/README.md",
        "/LICENSE",
        "/src/**",
        "/tests/**",
        "/examples/**",
        "fonts/small.flf",
        "fonts/banner.flf",
        "fonts/standard.flf",
        "fonts/frango.flc",
        "fonts/upper.flc",
        "fonts/utf8.flc",
        "fonts/hz.flc",
        "fonts/646-de.flc",
        "fonts/jis0201.flc",
]
categories = ["text-processing", "command-line-utilities"]

[lib]
name = "figdriver"
path = "src/lib.rs"

[[bin]]
name = "figlet"
path = "src/bin/figlet/main.rs"
doc = false
required-features = ["cli"]

[[test]]
name = "align_flags"
required-features = ["cli"]

[[test]]
name = "information_flags"
required-features = ["cli"]

[[test]]
name = "invalid_flag"
required-features = ["cli"]

[[test]]
name = "last_flag_wins"
required-features = ["cli"]

[[test]]
name = "smush_flags"
required-features = ["cli"]

[[test]]
name = "terminal_width"
required-features = ["cli"]

[[test]]
name = "whitespace_tokenization"
required-features = ["cli"]

[[test]]
name = "figlist"
required-features = ["cli"]

[[test]]
name = "showfigfonts"
required-features = ["cli"]

[[test]]
name = "stdin_line_endings"
required-features = ["cli"]

[features]
default = []
cli = ["dep:pico-args", "dep:terminal_size"]

[dependencies]
unicode-width = "0.2"
zip = { version = "8", default-features = false, features = ["deflate"] }

[dependencies.pico-args]
version = "0.5"
features = ["combined-flags", "short-space-opt", "eq-separator"]
optional = true

[dependencies.terminal_size]
version = "0.4"
optional = true

[dev-dependencies]
tempfile = "3"

[profile.release]
lto = true
