.TH FIGLIST 1 "June 2026" "FIGdriver\-rs 0.3" "User Commands"
.SH NAME
figlist \- list FIGfont and control files in a font directory
.SH SYNOPSIS
.B figlist
[options]
.SH DESCRIPTION
.B figlist
lists all FIGfont (.flf, .tlf) and control files (.flc) present in the
configured font directory. It also reports the default font name and the
font directory path currently in use.
.SH OPTIONS
.B figlist
processes options from left to right; when conflicting options are given,
the last one takes effect.
.TP
.B "\-d, \-\-fontdir"
.IR fontdirectory
Set the font search directory. Defaults to
.IR /usr/share/figlet .
.TP
.B "\-v, \-\-version"
Print the version and exit.
.TP
.B "\-h, \-\-help"
Print usage information and exit.
.SH OUTPUT
The output includes the default font name, the font directory path,
all FIGfont files with their file extensions stripped, and all control
files are listed alphabetically with their file extensions stripped.
.SH EXAMPLES
.PP
List fonts in the default directory:
.RS
.nf
figlist
.RE
.PP
List fonts in a custom directory:
.RS
.nf
figlist \-d /usr/share/fonts/figlet
.RE
.SH ENVIRONMENT
.TP
.B FIGLET_FONTDIR
If set, use the given directory as the default font search directory, instead
of
.IR /usr/share/figlet .
This can be overridden with
.BR \-d .
.SH FILES
.TP
.I /usr/share/figlet
Default directory searched for fonts and control files.
.SH NOTES
Unlike the reference figlist, which returns exit status 0 when the font
directory cannot be opened, this implementation returns exit status 1
and prints an error message to stderr.
.SH BUGS
Report bugs at <https://github.com/cmatsuoka/figdriver-rs/issues>.
.SH AUTHORS
This
.I figlist
implementation is written by Claudio Matsuoka, based on the original
FIGlet project by Glenn Chappell, Ian Chai, and John Cowan.
